PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?s WHERE {
	?s a owl:Class .
	FILTER NOT EXISTS { ?s rdfs:label ?label }
	FILTER(!isBlank(?s))
}