zooma_annotate: "http://192.168.0.199:8009/zooma/v2/api/services/annotate?propertyValue="
oxo_mapping: "https://mapping.ihccglobal.app/api/mappings?fromId="
ols_term: "https://registry.ihccglobal.app/api/terms?iri="
ols_oboid: "https://registry.ihccglobal.app/api/terms?obo_id="
min_match_probability: 0.1
rescale_nlp_matches:
  low: 0
  high: 0.9
zooma_confidence_mappings:
  LOW: 0.51
  MEDIUM: 0.76
  GOOD: 0.98
  HIGH: 1
